spring:
  application:
    name: navigant-backend
  
  # Active Profile
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Logging
  output:
    ansi:
      enabled: always

# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Custom App config
app:
  env: ${APP_ENV:development}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}


